StaminaIO/StaminaIO/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('index')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/equipamentos/', include('equipamento.urls')),
    path('api/pessoa/', include('pessoa.urls')),
    path('api/suplementos/', include('suplemento.urls')),
]

StaminaIO/accounts/urls.py
from django.urls import path
from . import views
from .views import custom_auth_token
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'accounts'

urlpatterns = [
    path('add/', views.createusu, name='add-user'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('api/token/', obtain_auth_token, name='api_token_auth'),
]

StaminaIO/pessoa/urls.py
# pessoa/urls.py

from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AlunoViewSet, FuncionarioViewSet

app_name = 'pessoa'

router = DefaultRouter()
router.register(r'alunos', AlunoViewSet)
router.register(r'funcionarios', FuncionarioViewSet)
urlpatterns = [

    #path('alunos/', views.listar_alunos, name='listar_alunos'),
    #path('alunos/adicionar/', views.adicionar_aluno, name='adicionar_aluno'),
    #path('alunos/editar/<int:pk>/', views.editar_aluno, name='editar_aluno'),
    #path('alunos/deletar/<int:pk>/', views.deletar_aluno, name='deletar_aluno'),

    #path('alunos/pagar/<int:aluno_id>/', views.pagar_mensalidade, name='pagar_mensalidade'),
    #path('pagamento/<int:pagamento_id>/deletar/', views.deletar_pagamento, name='deletar_pagamento'),
    #path('alunos/<int:aluno_id>/pagamentos/', views.listar_pagamentos_aluno, name='listar_pagamentos_aluno'),
    #path('alunos/selecionar-pagamentos/', views.selecionar_aluno_pagamentos, name='selecionar_aluno_pagamentos'),

    #path('funcionarios/', views.listar_funcionarios, name='listar_funcionarios'),
    #path('funcionarios/adicionar/', views.adicionar_funcionario, name='adicionar_funcionario'),
    #path('funcionarios/editar/<int:pk>/', views.editar_funcionario, name='editar_funcionario'),
    #path('funcionarios/deletar/<int:pk>/', views.deletar_funcionario, name='deletar_funcionario'),

    path('', include(router.urls)), 
]

StaminaIO/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - StaminaIO</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/logo.png'%}" rel="icon">
  <link href="{% static 'img/logo.png' %}" rel="apple-touch-icon">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">



  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Russo+One&display=swap" rel="stylesheet">
  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

  
  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">

</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
  
      <div class="d-flex align-items-center justify-content-between">
        <a href="/dashboard/" class="logo d-flex align-items-center">
            <span class="d-none d-lg-block">StaminaIO</span>
            <img src="{% static 'img/logo.png' %}" alt="" />
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
  
      
  
      <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
          <li class="nav-item dropdown">
  
            <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
              <i class="bi bi-bell"></i>
              <span class="badge bg-primary badge-number"></span>
            </a><!-- End Notification Icon -->
  
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
              <li class="dropdown-header">
                Sem notificações no momento
            </ul><!-- End Notification Dropdown Items -->
  
          </li><!-- End Notification Nav -->
  
          <li class="nav-item dropdown">
  
            <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
              <i class="bi bi-chat-left-text"></i>
            </a><!-- End Messages Icon -->
  
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
              <li class="dropdown-header">
                Sem mensagens no momento
              </li>
            </ul><!-- End Messages Dropdown Items -->
  
          </li><!-- End Messages Nav -->
  
          <li class="nav-item dropdown pe-3">
  
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <img src="{% static 'img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
              <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.username}}</span>
            </a><!-- End Profile Image Icon -->
  
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li class="dropdown-header">
                <h6>{{request.user.username}}</h6>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                  <i class="bi bi-gear"></i>
                  <span>Configurações</span>
                </a>
              </li>
  
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Sair</span>
                </a>
            </li>
            </ul><!-- End Profile Dropdown Items -->
  
          </li><!-- End Profile Nav -->
  
        </ul>
      </nav><!-- End Icons Navigation -->
  
    </header><!-- End Header -->
  
    {% include "_sidebar.html" %}

    <main id="main" class="main">
      {% block content %}
      {% endblock %}
    </main>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
      <div class="copyright">
        &copy; Copyright <strong><span>StaminaIO</span></strong>. Todos os Direitos Reservados
      </div>
    </footer><!-- End Footer -->
  
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  
    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/chart.min.js' %}"></script>
    <script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  
    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
  
  </body>
  
  </html>

StaminaIO/templates/_sidebar.html
{% load static %}
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'index' %}">
        <i class="bi bi-house-door"></i>
        <span>Dashboard</span>
      </a>
    </li>
    <li class="nav-heading">Páginas</li>

    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'listar_funcionarios' %}active{% endif %}" href="{% url 'pessoa:listar_funcionarios' %}">
        <i class="bi bi-person-fill"></i>
        <span>Funcionários</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'listar_alunos' %}active{% endif %}" href="{% url 'pessoa:listar_alunos' %}">
        <i class="bi bi-person-lines-fill"></i>
        <span>Alunos</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'listar_equipamentos' %}active{% endif %}" href="{% url 'equipamento:listar_equipamentos' %}">
        <i class="bi bi-box-seam"></i>
        <span>Equipamentos</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'listar_suplementos' %}active{% endif %}" href="{% url 'suplemento:listar_suplementos' %}">
        <i class="bi bi-capsule"></i>
        <span>Suplementos</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'selecionar_aluno_pagamentos' %}active{% endif %}" href="{% url 'pessoa:selecionar_aluno_pagamentos' %}">
        <i class="bi bi-currency-dollar"></i>
        <span>Pagamentos</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if request.resolver_match.url_name == 'add-user' %}active{% endif %}" href="{% url 'accounts:add-user' %}">
        <i class="bi bi-person-plus"></i>
        <span>Cadastro de Usuário</span>
      </a>
    </li>
    
  </ul>
</aside>